### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by elazzour** [Legimet/nPDF#15] opened 2016-01-09 22:35 UTC
Hello dear friend. First of all, I would like to congratulate you on the work you have done on the subject of npdf, however, I would like to know whether you think that there will be a search option in the future, as it is the only thing missing. Either way, thank you and great job.

**Comment by Legimet** [comment] 2016-01-09 23:14
This is a duplicate of #13.
And yes, I plan to make searching available in the next version.

**Closed** 2016-01-09 23:15 UTC
Labels: duplicate

**Comment by elazzour** [comment] 2016-01-10 00:18
oh i'm very sorry for the duplicate :( and thank you for the answer
